spring:
  freemarker:
    suffix: ".ftl"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5454/debts}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}